-- Tesla Overload — EMP-locks and zaps enemy buildings near your units.
--
-- By default this is NOT a map-wide cheat: the "overload" only reaches enemy
-- buildings within OVERLOAD_RADIUS cells of a living player/allied unit. Set
-- DEBUG_MAP_WIDE = true only to stress-test the mechanic quickly.
--
-- What changed vs. the old build:
--   * DEBUG_MAP_WIDE now defaults to false (real radius mechanic).
--   * Zaps use an electric warhead (WARHEAD); the native fallback chain keeps
--     it safe if an ID is missing from the rules.
--   * Overload is only generated by a Tesla-capable unit of the player's side
--     (GENERATOR_TYPES) — a plain Conscript/infantry does not conduct the zap.
--   * Allied houses still count as generators, not only the player's exact house.
--   * All engine calls are pcall-guarded and re-validated; the building name is
--     read BEFORE the damaging zap so a building that dies mid-pulse is never
--     derefed again (no stale-ref).
--   * Per-hit LuaAPI.log spam replaced by a throttled aggregate pulse log.
--   * After "victory" the mod recovers if new enemy buildings appear.

local TeslaOverload = {}

-- Config ------------------------------------------------
local DEBUG_MAP_WIDE   = false   -- true = every enemy building on the map (test/cheat)
local OVERLOAD_RADIUS  = 8.0     -- cells: aura reach around your units
local DAMAGE_PER_PULSE = 40      -- HP per zap
local PULSE_INTERVAL   = 45      -- frames between pulses (~0.75 s)
local EMP_FRAMES       = 45      -- blackout/paralysis duration per zap
local WARHEAD          = "TTankWH"  -- electric warhead; fallback-chain safe if absent
local SUMMARY_LOG_EVERY = 180    -- frames between the throttled aggregate log lines

-- Only these unit types conduct the overload ("Tesla"). A plain infantryman
-- (e.g. a Conscript) or any non-Tesla vehicle does NOT generate the zap even if
-- it is the player's side and near an enemy building.
local GENERATOR_TYPES = {
    TTNK = true,  -- Tesla Tank (repo-confirmed ID)
    -- e.g. Tesla Trooper infantry ID here if desired.
}

local NEUTRAL_HOUSES = { Neutral = true, Civilian = true, Special = true }

local lastPulseFrame = 0
local lastSummaryLog = 0
local victoryLogged  = false

local function msg(text)
    if Engine and Engine.PrintMessage then
        Engine.PrintMessage(text)
    end
end

-- Is `ownerHouse` a hostile house of `player` (not self, not ally, not neutral)?
local function isEnemyHouse(player, ownerHouse)
    if not ownerHouse then
        return false
    end
    local okName, name = pcall(ownerHouse.GetName, ownerHouse)
    if okName and NEUTRAL_HOUSES[name] then
        return false
    end
    local okAllied, allied = pcall(ownerHouse.IsAlliedWith, ownerHouse, player)
    return okAllied and allied == false
end

-- Is `unit` on the player's side (self- or allied-owned)?
local function isPlayerSide(player, unit)
    if not unit or not unit:IsAlive() then
        return false
    end
    local ok, owner = pcall(unit.GetOwner, unit)
    if not ok or not owner then
        return false
    end
    if owner == player then
        return true
    end
    local okSelf, selfAlly = pcall(owner.IsAlliedWith, owner, player)
    return okSelf and selfAlly == true
end

-- Only a Tesla-capable unit (of the player's side) can generate an overload.
local function isGenerator(player, unit)
    if not isPlayerSide(player, unit) then
        return false
    end
    local ok, typeName = pcall(unit.GetTypeName, unit)
    return ok and typeName and GENERATOR_TYPES[typeName] == true
end

function TeslaOverload.Update(frame)
    if frame - lastPulseFrame < PULSE_INTERVAL then
        return
    end
    lastPulseFrame = frame

    local player = House.GetPlayer()
    if not player then
        return
    end

    local okB, buildings = pcall(World.GetBuildings)
    if not okB or not buildings then
        return
    end
    local okU, units = pcall(World.GetUnits)
    if not okU or not units then
        return
    end

    -- Units that can generate the overload: player's side AND Tesla-capable.
    local charged = {}
    for _, u in ipairs(units) do
        if isGenerator(player, u) then
            charged[#charged + 1] = u
        end
    end

    -- Any living enemy building left?
    local enemyCount = 0
    for _, bld in ipairs(buildings) do
        if bld:IsAlive() then
            local ok, owner = pcall(bld.GetOwner, bld)
            if ok and isEnemyHouse(player, owner) then
                enemyCount = enemyCount + 1
            end
        end
    end

    if enemyCount == 0 then
        if not victoryLogged then
            victoryLogged = true
            print("[LuaAPI] No enemy buildings remain. Tesla Overload standing by.")
            msg("All enemy structures destroyed!")
        end
        return
    end
    victoryLogged = false

    -- In radius mode we need at least one nearby generator unit.
    if not DEBUG_MAP_WIDE and #charged == 0 then
        return
    end

    local hits = 0
    for _, bld in ipairs(buildings) do
        if bld:IsAlive() then
            local ok, owner = pcall(bld.GetOwner, bld)
            if ok and isEnemyHouse(player, owner) then

                local inRange = DEBUG_MAP_WIDE
                if not inRange then
                    for _, u in ipairs(charged) do
                        local okD, d = pcall(u.GetDistanceTo, u, bld)
                        if okD and d and d <= OVERLOAD_RADIUS then
                            inRange = true
                            break
                        end
                    end
                end

                if inRange then
                    -- Read the name BEFORE damaging: the zap may kill the building,
                    -- and we must not deref the object again afterwards.
                    local okN, name = pcall(bld.GetTypeName, bld)
                    local bldName = tostring(okN and name or "?")

                    pcall(bld.Disable, bld, EMP_FRAMES)
                    local okT, hpLeft = pcall(bld.TakeDamage, bld, DAMAGE_PER_PULSE, WARHEAD)

                    if okT then
                        hits = hits + 1
                        if hits <= 2 then
                            msg(string.format("⚡ [Tesla Overload] %s EMP-locked! HP: %d",
                                bldName, tonumber(hpLeft) or 0))
                        end
                    end
                end
            end
        end
    end

    -- Throttled aggregate log so LuaAPI.log is not flooded every pulse.
    if hits > 0 and (frame - lastSummaryLog) >= SUMMARY_LOG_EVERY then
        lastSummaryLog = frame
        print(string.format("[LuaAPI] ⚡ [Tesla Overload] zapped %d enemy building(s)",
            hits))
    end
end

return TeslaOverload
